hashter/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
	title = StringField('title', validators=[DataRequired()])
	content = TextAreaField('content', validators=[DataRequired()])
	picture = FileField('photo', validators=[FileAllowed(['jpg', 'png', 'gif'])])
	key = StringField('key', validators=[Length(min=0, max=20)])
	submit = SubmitField('post')

class CommentForm(FlaskForm):
	content = TextAreaField('reply', validators=[DataRequired()])
	key = StringField('key to encrypt comment', validators=[Length(min=0, max=20)])
	submit = SubmitField('add reply')

class DecryptForm(FlaskForm):
	key = StringField('key', validators=[DataRequired()])
	submit = SubmitField('decrypt?')

hashter/posts/routes.py
import base64
import os
from flask import (render_template, current_app, url_for, flash, redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from hashter import db
from hashter.models import Post, Comment, User
from hashter.posts.forms import PostForm, CommentForm, DecryptForm
from hashter.posts.utils import (save_post_picture, save_encrypted_post_picture, decrypt_picture,
									get_key, encryptAES_CBC, decryptAES_CBC, randomName)
from hashter.users.utils import delete_temp_image


posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
	form = PostForm()
	picture_file = None
	if current_user.temp_image:
		delete_temp_image()
	if form.validate_on_submit():
		if form.key.data:
			message = form.content.data
			message_key = get_key(form.key.data)
			if form.picture.data:
				picture_file = save_encrypted_post_picture(message_key, form.picture.data)
			ciphertext = encryptAES_CBC(message_key, message)
			post = Post(title=form.title.data, content=ciphertext, length=len(ciphertext), 
						image_file=picture_file, author=current_user, encryption=True, short_content=ciphertext[:300])
			db.session.add(post)
			db.session.commit()
			flash('a secret', 'success')
		else:
			if form.picture.data:
				picture_file = save_post_picture(form.picture.data)
			post = Post(title=form.title.data, content=form.content.data, length=len(form.content.data), 
						image_file=picture_file, author=current_user, encryption=False, short_content=form.content.data[:500])
			db.session.add(post)
			db.session.commit()
			flash('no key created', 'success')
		return redirect(url_for('main.home'))
	return render_template('create_post.html', title='speak', form=form, legend='speak')

@posts.route("/post/<int:post_id>", methods=['GET','POST'])
@login_required
def post(post_id):
	if current_user.temp_image:
		delete_temp_image()
	form= DecryptForm()
	form2 = CommentForm()
	post = Post.query.get_or_404(post_id)
	comment_encrypted_names = []
	comments = Comment.query.filter_by(post=post)
	for comment in comments:
		name = comment.author.username
		comment_encrypted_name = randomName(name)
		comment_encrypted_names.append(comment_encrypted_name)
	encrypted_name = randomName(post.author.username)
	
	if post.encryption == False:
		form = None
	elif post.encryption == True:
		if post.image_file:
			filename = post.image_file
			user  = current_user
			if form.validate_on_submit():
				post_key = get_key(form.key.data)
				new_image = decrypt_picture(post_key, filename)
				message = decryptAES_CBC(post_key, post.content)
				user.temp_image = new_image
				flash(f'message is { message }', 'whole success')
				db.session.commit()
				return redirect(url_for('posts.decrypted', post_id=post.id))
		if form.validate_on_submit():
			post_key = get_key(form.key.data)
			post_ciphertext = post.content
			message = decryptAES_CBC(post_key, post_ciphertext)
			flash(f'message is { message }', 'success')
		elif form.errors:
			flash(f'mustnt be it', 'success')
	if form2.validate_on_submit():
		if form2.key.data:
			message = form2.content.data
			comment_key = get_key(form2.key.data)
			ciphertext = encryptAES_CBC(comment_key, message)
			comment = Comment(content=ciphertext, author=current_user, post=post)
		else:
			comment=Comment(content=form2.content.data, author=current_user, post=post)
		db.session.add(comment)
		db.session.commit()
		flash('comment added', 'success')
		return redirect(url_for('posts.post', post_id=post_id))
	return render_template('post.html', title=post.title, post=post, 
							form=form, comment_encrypted_names=comment_encrypted_names, 
							encrypted_name=encrypted_name, form2=form2, comments=comments)

@posts.route("/post/<int:post_id>/update", methods=['GET','POST'])
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	if current_user.temp_image:
		delete_temp_image()
	if post.author != current_user:
		abort(403)
	form = PostForm()
	if form.validate_on_submit():
		if form.key.data:
			message = form.content.data
			message_key = get_key(form.key.data)
			ciphertext = encryptAES_CBC(message_key, message)
			post.title = form.title.data
			post.content = ciphertext
			db.session.commit()
			flash('a secret', 'success')
			return redirect(url_for('posts.post', post_id = post.id))
		else:
			post.title = form.title.data
			post.content = form.content.data
			db.session.commit()
			flash('revolving revolved', 'success')
			return redirect(url_for('posts.post', post_id = post.id))
	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template('create_post.html', title='revolve', form=form, legend='revolve')

@posts.route("/post/<int:post_id>/delete", methods=['GET','POST'])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	elif post.comments:
		if post.image_file:
			os.remove(os.path.join(current_app.root_path, 'static/post_pics', post.image_file))
			post.image_file = None
		post.content = "(deleted)"
		post.short_content = "(deleted)"
		db.session.commit()
	else:
		if post.image_file:
			os.remove(os.path.join(current_app.root_path, 'static/post_pics', post.image_file))
		db.session.delete(post)
		db.session.commit()
		flash('exitium', 'success')
	return redirect(url_for('main.home'))

@posts.route("/comment/<int:comment_id>/delete", methods=['GET','POST'])
@login_required
def delete_comment(comment_id):
	comment = Comment.query.get_or_404(comment_id)
	if comment.author != current_user:
		abort(403)
	else:
		db.session.delete(comment)
		db.session.commit()
		flash('comment exitium', 'success')
		return redirect(url_for('main.home'))
	

@posts.route("/decrypted/<post_id>", methods=['GET', 'POST'])
@login_required
def decrypted(post_id):
	user = current_user
	post = Post.query.get_or_404(post_id)
	return render_template('decrypted.html', user=current_user, post=post)

@posts.route("/deluge")
def everything():
	if current_user.is_authenticated:
		if current_user.temp_image:
			delete_temp_image()
		tribe = current_user.tribe
		page = request.args.get('page', 1, type=int)
		posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
		encrypted_names = []
		for post in posts.items:
			name = post.author.username
			encrypted_name = randomName(name)
			encrypted_names.append(encrypted_name)

		return render_template('deluge.html', posts=posts, tribe=tribe, encrypted_names=encrypted_names)
	else:
		return render_template('unregistered.html')

hashter/users/routes.py
import os
import datetime as dtime
from datetime import datetime
from flask import render_template, url_for, flash, redirect, request ,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from hashter import db, bcrypt
from hashter.models import User, Post, Comment, Invitation
from hashter.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, 
								RequestResetForm, ResetPasswordForm, InviteFriendForm, CreateInviteForm)
from hashter.users.utils import (save_picture, send_reset_email,rotate_picture, 
								send_invite_email, generateInvite, delete_temp_image, add_villager, ostracize)

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET','POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('users.logout'))
	form=RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password, members=0)
		db.session.add(user)
		db.session.flush()
		if user.id == 1:
			db.session.commit()
			flash(f'welcome back again zalazalaza your username is {form.username.data} your id is {user.id}', 'success')
			return redirect(url_for('users.login'))
		elif user.id > 1:
			invite_confirm = Invitation.query.filter_by(invitation=form.invitation.data).first()
			if invite_confirm:
				creator = invite_confirm.creator
				user.tribe.append(creator)
				add_villager(user)
				if creator.members < 100:
					creator.tribe.append(user)
					add_villager(creator)
				elif creator.members >= 100:
					flash(f'{ creator.username } has too many friends', 'success')
				db.session.delete(invite_confirm)
				db.session.commit()
				flash(f'account created for {form.username.data}. you can now log in', 'success')
				return redirect(url_for('users.login'))
			else:
				db.session.close()
				flash('wrong code kid', 'success')
				return redirect(url_for('users.register'))
		else:
			flash('whats the password?', 'alert')
			return redirect(url_for('users.register'))
	return render_template('register.html', title='register', form=form)

@users.route("/register/<token>", methods=['GET','POST'])
def token_register(token):
	if current_user.is_authenticated:
		return redirect(url_for('users.logout'))
	user = User.verify_token(token)
	if user is None:
		flash('bad token', 'alert')
		return redirect(url_for('users.unregistered'))
	email_user = User.verify_invite_token(token)
	if email_user:
		flash('email already in use', 'alert')
		return redirect(url_for('users.login'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		
		user_new = User(username=form.username.data, email=form.email.data, password=hashed_password, members=0)
		db.session.add(user_new)
		db.session.commit()
		if user:
			if user.members < 100:
				add_villager(user)
				add_villager(user_new)
				user_new.tribe.append(user)
				user.tribe.append(user_new)
				db.session.commit()
				flash('welcome home', 'success')
			if user.members >= 100:
				user_new.tribe.append(user)
				db.session.commit()
				add_villager(user_new)
				flash(f'you have them but they dont have you. account created { form.username.data }', 'success')
		return redirect(url_for('users.login'))
	return render_template('token_register.html', title='forget something?', form=form)

@users.route("/unregistered", methods=['GET','POST'])
def unregistered():
	if current_user.is_authenticated:
		return redirect(url_for('users.logout'))
	return render_template('unregistered.html', title='no name')

@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form=LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			flash(f'your wish is my command { current_user.username }', 'success')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('login unsuccessful , check yr info', 'bad')

	return render_template('login.html', title='log in', form=form)

@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('users.login'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	if current_user.is_authenticated:
		form = UpdateAccountForm()
		if current_user.temp_image:
			delete_temp_image()
		if form.validate_on_submit():
			if form.picture.data:
				picture_file = save_picture(form.picture.data)
				current_user.image_file = picture_file
			if form.rotate.data:
				picture_file = rotate_picture()
				current_user.image_file = picture_file
			if form.display.data:
				if current_user.display == 1:
					current_user.display = 0
				elif current_user.display == 0:
					current_user.display = 1
				else:
					current_user.display = 0	
			current_user.username = form.username.data
			current_user.email = form.email.data
			db.session.commit()
			flash('your account has been updated', 'alert')
			return redirect(url_for('users.account'))
		elif request.method == 'GET':
			form.username.data = current_user.username
			form.email.data = current_user.email
		image_file = url_for('static', filename='profile_pics/'+ current_user.image_file)
		return render_template('account.html', title='account', 
							image_file=image_file, form=form)
	else:
		return render_template('unregistered')

@users.route("/user/<string:username>")
def user_posts(username):
	if current_user.is_authenticated:
		if current_user.temp_image:
			delete_temp_image()
		page = request.args.get('page', 1, type=int)
		user = User.query.filter_by(username=username).first_or_404()
		posts = Post.query.filter_by(author=user)\
			.order_by(Post.date_posted.desc())\
			.paginate(page=page, per_page=5)
		return render_template('user_posts.html', posts=posts, user=user)
	else:
		return render_template('unregistered.html')

@users.route("/reset_password", methods=['GET','POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('check your email', 'success')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html', title='forget something?', form=form)

@users.route("/reset_password/<token>", methods=['GET','POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_token(token)
	if user is None:
		flash('bad token', 'alert')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash('remembered', 'success')
		return redirect(url_for('users.login'))
	return render_template('reset_token.html', title='forget something?', form=form)

@users.route("/tribe/text", methods=['GET', 'POST'])
@login_required
def hand_invite():
	if current_user.is_authenticated:
		if current_user.temp_image:
			delete_temp_image()
		tribe = current_user.tribe
	form2 = CreateInviteForm()
	if form2.validate_on_submit():
		tdelta = dtime.timedelta(days=30)
		if current_user.invitations:
			stamp = current_user.invite_timestamp + tdelta
			if current_user.id == 1 and current_user.username == "zalazalaza":
				invite = generateInvite()
				invitation = Invitation(invitation=invite, user_id=current_user.id)
				db.session.add(invitation)
				db.session.commit()
				flash(f'hello zalazalaza {invite} is your new code. write it down', 'success')
				return redirect(url_for('users.hand_invite'))

			if stamp >= datetime.utcnow() and current_user.invitations < 10:
				invite = generateInvite()
				invitation = Invitation(invitation=invite, user_id=current_user.id)
				current_user.invitations += 1
				db.session.add(invitation)
				db.session.commit()
				flash(f'{invite} is your new code. write it down. you have {10 - current_user.invitations} invitations left', 'success')
				return redirect(url_for('users.hand_invite'))
			elif stamp < datetime.utcnow():
				invite = generateInvite()
				invitation = Invitation(invitation=invite, user_id=current_user.id)
				current_user.invitations = 1
				current_user.invite_timestamp = datetime.urcnow()
				db.session.add(invitation)
				db.session.commit()
				flash(f'{invite} is your code. Youve been patient and now have 10 more invites', 'success')
				return redirect(url_for('users.hand_invite'))
			elif current_user.invitations >= 10:
				flash('too many too soon', 'success')
				return redirect(url_for('main.home'))
		else:
			invite = generateInvite()
			invitation = Invitation(invitation=invite, user_id=current_user.id)
			current_user.invitations = 1
			current_user.invite_timestamp = datetime.utcnow()
			db.session.add(invitation)
			db.session.commit()
			flash(f'{invite} is your new code. write it down', 'success')
			return redirect(url_for('users.hand_invite'))
	return render_template('hand_tribe.html', title='size', tribe=tribe, form2=form2)


@users.route("/tribe", methods=['GET', 'POST'])
@login_required
def invite():
	if current_user.is_authenticated:
		if current_user.temp_image:
			delete_temp_image()
		tribe = current_user.tribe
		form = InviteFriendForm()
		if form.validate_on_submit():
			tdelta = dtime.timedelta(days=30)
			new_user = User.query.filter_by(email=form.email.data).first()
			if new_user:
				if new_user in current_user.tribe:

hashter/templates/chat.html
{% extends "chat_template.html" %}
{% block content %}
	{{ name }}
	<script class='mini-text' type="text/javascript">
		$(document).ready(function() {
			var socket = io.connect('127.0.0.1:5000');

			socket.on('connect', function() {
				socket.send('User has connected');
				$('#myMessage').val('');
			});

			socket.on('message', function(msg) {
				$("#messages").append('<li>'+msg+'</li>');
			});

			$('#sendbutton').on('click', function() {
				socket.send($('#myMessage').val());
				$('#myMessage').val('');
			});

			$(document).keypress(function(e) {
				if(e.which == 13) {
					socket.send($('#myMessage').val());
					$('#myMessage').val('');
				}

			});

		});
	</script>
	<ul class="mini-text undecorated" id="messages"> </ul>
	<input class='form-control text-10px' type="text" id="myMessage">
	<button class='small-button' id="sendbutton">send</button>
{% endblock content %}
	

hashter/templates/deluge.html
{% extends "layout.html" %}
{% block content %}
	{% for post in posts.items %}
		<div class="home">
			{% if post.author in tribe or post.author==current_user %}
				<div class="metadata">
					<img class=" pb-3 left very-small-round" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
					<a class="title-name" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{  post.author.username }}</a>
					<small class="title-title"> posted </small>
					<a class="title-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }} </a>
					<small class="title-date">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
				</div>
			{% else %}
				<div class="metadata">
					<img class=" pb-3 left very-small-round" src="{{ url_for('static', filename='profile_pics/tenofcups.png') }}">
					<a class="title-name" href="{{ url_for('main.home') }}">{{  encrypted_names[loop.index-1] }}</a>
					<small class="title-title"> posted </small> 
					<a class="title-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }} </a>
					<small class="title-date">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
				</div>
			{% endif%}
					
				

			<div class="">
			
				{% if post.image_file %}
					{% if post.length < 400 %}
						<img class="picture-small-posts" src="{{ url_for('static', filename='post_pics/' + post.image_file) }}" onerror="this.src='../static/post_pics/tenofcups.png'"/>
						<p class="wrap">{{ post.content }} {{ post.length }}<a class="smaller right red" href="{{ url_for('posts.post', post_id=post.id) }}">(inspect)</a></p>

					{% elif post.length < 1100 %}
						<img class="left picture-mini" src="{{ url_for('static', filename='post_pics/' + post.image_file) }}" onerror="this.src='../static/post_pics/tenofcups.png'"/>
						<p class="wrap">{{ post.content }} {{ post.length }}<a class="smaller right red" href="{{ url_for('posts.post', post_id=post.id) }}">(inspect)</a></p>
					
					{% else %}
						<img class="left picture-large" src="{{ url_for('static', filename='post_pics/' + post.image_file) }}" onerror="this.src='../static/post_pics/tenofcups.png'"/>
						<p class="wrap">{{ post.content }} {{ post.length }}<a class="smaller right red" href="{{ url_for('posts.post', post_id=post.id) }}">(inspect)</a></p>
						
					{% endif %}
				{% else %}
					<p class="wrap">{{ post.content }}<a class="smaller right red" href="{{ url_for('posts.post', post_id=post.id) }}">(inspect)</a></p>
				{% endif %}
			</div>
		</div>
		
	{% endfor %}
	
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=3) %}
		{% if page_num %}
			<div class="inline padb-250">
				{% if posts.page == page_num %}
					{% if page_num == 1 %}
						<a class="small-button ml" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
					{% else %}
						<a class="small-button" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
					{% endif %}
				{% else %}
					{% if page_num == 1 %}
						<a class="small-plain ml" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
					{% else %}	
						<a class="small-plain" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
					{% endif %}
				{% endif %}
			</div>
			
		{% else %}
			...
		{%endif %}
	{% endfor %}
{% endblock content %}

hashter/templates/hand_tribe.html
{% extends "layout.html" %}
{% block content %}
	

	<form method="POST" action="">
		{{ form2.hidden_tag() }}
		<div class="ml form-group">
			<a href="#">{{ form2.submit(class="small-button") }}</a>
		</div>
	</form>
	
{% endblock content %}
	

hashter/templates/home.html
{% extends "layout.html" %}
{% block content %}
	{% for post in posts.items %}
		{% if post.author in tribe or post.author==current_user %}
			<div class="home">
				
				<div class="metadata">
					<img class=" pb-3 left very-small-round" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
					<a class="title-name" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{  post.author.username }}</a>
					<small class="title-title"> posted </small>
					<a class="title-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }} </a>
					<small class="title-date">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
				</div>

				<div class="">
				
					{% if post.image_file %}
						{% if post.length < 470 %}
							<a href="{{ url_for('posts.post', post_id=post.id)}}"><img class="picture-small-posts" src="{{ url_for('static', filename='post_pics/' + post.image_file) }}" onerror="this.src='../static/post_pics/tenofcups.png'"/></a>
							<p class="wrap">{{ post.short_content }}<a class="smaller right red" href="{{ url_for('posts.post', post_id=post.id) }}">(inspect)</a></p>
						{% else %}
							<a href="{{ url_for('posts.post', post_id=post.id) }}"><img class="picture-mini" src="{{ url_for('static', filename='post_pics/' + post.image_file) }}" onerror="this.src='../static/post_pics/tenofcups.png'"/></a>
							<p class="wrap">{{ post.short_content }}<a class="smaller right red" href="{{ url_for('posts.post', post_id=post.id) }}">(inspect)</a></p>
						{% endif %}
					{% else %}
						<p class="wrap">{{ post.short_content }}<a class="smaller right red" href="{{ url_for('posts.post', post_id=post.id) }}">(inspect)</a></p>
					{% endif %}
					
		

				</div>
					
				
			</div>
		{% endif %}
	{% endfor %}
	
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=3) %}
		{% if page_num %}
			<div class="inline padb-250">
				{% if posts.page == page_num %}
					{% if page_num == 1 %}
						<a class="small-button ml" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
					{% else %}
						<a class="small-button" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
					{% endif %}
				{% else %}
					{% if page_num == 1 %}
						<a class="small-plain ml" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
					{% else %}	
						<a class="small-plain" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
					{% endif %}
				{% endif %}
			</div>
			
		{% else %}
			...
		{%endif %}
	{% endfor %}
{% endblock content %}

hashter/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% if current_user.display == 1 %}
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='whiteback.css') }}">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% elif current_user.display == 0 %}
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% else %}
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='whiteback.css') }}">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% endif %}



	{% if title %}
		<title>hashter - {{ title }}</title>
	{% else %}
		<title>hashter</title>
	{% endif %}
</head>
<body>
	<header id="main-header">
		{% if current_user.is_authenticated %}
			<img id="primary-pic" src="{{ url_for('static', filename='profile_pics/' +										current_user.image_file) }}">
		{% else %}
			<img id="primary-pic" src="{{ url_for('static', filename='profile_pics/tenofcups.png') }}">
		{% endif %}
		<pre id="logo"><a href="{{ url_for('users.login') }}">::   .:   :::.     .::::::.   ::   .: ::::::::::::.,:::::: :::::::..
 ,;;   ;;,  ;;`;;   ;;;`    `  ,;;   ;;,;;;;;;;;'''';;;;'''' ;;;;``;;;;
,[[[,,,[[[ ,[[ '[[, '[==/[[[[,,[[[,,,[[[     [[      [[cccc   [[[,/[[['
"$$$"""$$$c$$$cc$$$c  '''    $"$$$"""$$$     $$      $$""""   $$$$$$c
 888   "88o888   888,88b    dP 888   "88o    88,     888oo,__ 888b "88bo,
 MMM    YMMYMM   ""`  "YMmMY"  MMM    YMM    MMM     """"YUMMMMMMM   "W"</a></pre>
	</header>
	<nav id="navbar">

		<ul>
			<li><a href="{{ url_for('main.home') }}">home</a></li>
			<li><a href="{{ url_for('posts.everything') }}">deluge</a></li>
			<li><a href="{{url_for('posts.new_post') }}">post</a></li>
			<li><a href="{{ url_for('users.invite') }}">tribe</a></li>
			{% if current_user.is_authenticated %}
				<li><a href="{{url_for('users.account') }}">mine</a></li>
				<li><a href="{{url_for('users.logout') }}">logout</a></li>
			{% else %}
				<li><a href="{{url_for('users.register') }}">register</a></li>
				<li><a href="{{url_for('users.login') }}">login</a></li>
			{% endif %}
		</ul>
	</nav>

	<div class="blog-text">
		{%  with messages = get_flashed_messages(with_categories=true)%}
			{% if messages %}
				{% for category, message in messages %}
					<div class="alert alert-{{ category }}">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
		{% endwith %}
		{% block content %}{% endblock %}
	</div>
</body>
<script src="{{ url_for('static', filename='main.js') }}"></script>
</html>

hashter/templates/other_tribe.html
{% extends "layout.html" %}
{% block content %}
	<div class="ml">
		<h2> {{ user.username }}'s village</h2>
		<img class="picture-large" src="{{ url_for('static', filename='profile_pics/' +										user.image_file) }}">
		
	</div>
	<div class="">
		{% for person in tribe %}
			<div class='tribe ml-10'>
				<a class='' href="{{ url_for('users.user_posts', username=person.username) }}"><img class="medium-round" src="{{ url_for('static', filename='profile_pics/' + person.image_file) }}"></a>
				<div class='ml-20 mini-text'>{{ person.username }}</div>
				<a class="medium-button inline" href="{{ url_for('users.add_person', user_id = person.id ) }}" onclick="return confirm('add to village?');">add</a>
			</div>
		{% endfor %}
	</div>
	
	</div>


	
	
{% endblock content %}
	